apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  labels:
    app: nginx
    user: cfl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test1
        image: test
        ports:
        - containerPort: 80
