apiVersion: apps/v1
kind: Deployment
metadata:
  name: cflNginxTest
  labels:
    app: nginx
    user: cfl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cflNginxTest
  template:
    metadata:
      labels:
        app: cflNginxTest
    spec:
      containers:
      - name: cflNginxTest
        image: test
        ports:
        - containerPort: 80
