apiVersion: apps/v1
kind: Deployment

metadata:
  name: helm-test-dep
  labels:
    app: nginx
    user: cfl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helm-test
  template:
    metadata:
      labels:
        app: helm-test
    spec:
      containers:
      - name: helm-test
        image: registry.cn-beijing.aliyuncs.com/cfl-test/test-nginx
        ports:
        - containerPort: 80
