apiVersion: apps/v1
kind: Deployment

metadata:
  name: app2
  labels:
    app: app2
    user: cfl
spec:
  replicas: 2
  selector:  # deplyment 选择的 pod 标签 
    matchLabels:
      app: app2
  template:    # Template描述将要创建的pods。
    metadata:   
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: registry.cn-beijing.aliyuncs.com/cfl-test/app2:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-app2
spec:
  selector:
    app: app2
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress-app2
spec:
  rules:
  - host: www.app2.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc-app2
          servicePort: 80 
