apiVersion: apps/v1
kind: Deployment

metadata:
  name: test1
  labels:
    app: nginx
    user: cfl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test1
        image: registry.cn-beijing.aliyuncs.com/cfl-test/test-nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-test
spec:
  selector:
    name: test1
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: extensions/v1
kind: Ingress
metadata:
  name: nginx-ingress-test
spec:
  rules:
  - host: www.cfl.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc-test
          servicePort: 80 